FROM pagarme/docker-nodejs:8.9

RUN mkdir /tldr

COPY ./.env.cloud /tldr
COPY scripts/migrate /tldr
COPY package.json /tldr
COPY yarn.lock /tldr
COPY src /tldr

WORKDIR /tldr

RUN yarn install

EXPOSE 8888

CMD ["sh", "-c", "node bin/worker.js"]

