# Install npm dependencies
FROM pagarme/docker-nodejs:8.9

COPY .env /tldr/.env
COPY package.json /tldr
COPY start_server.sh /tldr
COPY start_worker.sh /tldr
COPY yarn.lock /tldr
COPY src /tldr
COPY views /tldr/views
COPY scripts/migrate /tldr

WORKDIR /tldr

RUN apk --update add --no-cache python make g++
RUN yarn install

# Build the application
FROM pagarme/docker-nodejs:8.9

ENV APP_NAME 'tldr'
ENV PORT 3000

COPY --from=0 /tldr /tldr

WORKDIR /tldr

EXPOSE ${PORT}
