FROM pagarme/docker-nodejs:8.9

RUN mkdir /tldr
RUN mkdir /tldr/views

COPY .env.cloud /tldr
COPY package.json /tldr
COPY yarn.lock /tldr
COPY src /tldr
COPY views /tldr/views

WORKDIR /tldr

RUN yarn install

EXPOSE 8888

CMD ["sh", "-c", "node bin/server.js"]

