#!/bin/sh

export $(cat .env | xargs)

if [[ "x$1" = "xundo" ]]; then
  node_modules/.bin/sequelize db:migrate:undo --config config/database.js --migrations-path database/migrations/
else
  node_modules/.bin/sequelize db:migrate --config config/database.js --migrations-path database/migrations/
fi

