#!/bin/bash

if [[ "x$1" = "xundo" ]]; then
  docker-compose run app node_modules/.bin/sequelize db:migrate:undo --config src/config/database.js --migrations-path src/database/migrations/
else
  docker-compose run app node_modules/.bin/sequelize db:migrate --config src/config/database.js --migrations-path src/database/migrations/
fi

